<a href="https://colab.research.google.com/github/lamnguyenkhang31231021496/ueh25_ktltsp_khanglam_st3/blob/main/Buoi_3_Phan_tich_du_lieu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
v = list(range(1,6))
print(v)
print(2*v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
import numpy as np
v = np.arange(1,6)
print(v)
print(2*v)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [3]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}

In [4]:
x = [60, 70, 80, 90]
print('len(x)=',len(x))
print('x[0]=',x[0])
print('x[1]=', x[1])
print('x[-1]=',x[-1])
print('x[1:3]=',x[1:3])

len(x)= 4
x[0]= 60
x[1]= 70
x[-1]= 90
x[1:3]= [70, 80]


In [5]:
from IPython.display import display
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print('c = ')
display(c)

c = 


array([ 4, 10, 18])

In [6]:
import numpy as np

a = np.zeros((2,2))
display(a)

b = np.ones((3,2))
display(b)

c = np.full((4,5),7)
display(c)

d = np.eye(4)
display(d)

e = np.random.random((2,2))
display(e)

array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[0.88390446, 0.98241967],
       [0.19031681, 0.7924586 ]])

In [7]:
import numpy as np
a = np.arange(15, dtype=float)
display(a)

a = a.reshape(3,5)
display(a)

display(a.shape)
display(a.ndim)
display(a.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

(3, 5)

2

dtype('float64')

In [8]:
import numpy as np
a = np.array([1,2,3,4,5])
display(a)

array([1, 2, 3, 4, 5])

In [9]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
display(a)
display(a.shape)
display(a.ndim)
display(a.dtype)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

(4, 5)

2

dtype('int64')

In [10]:
a = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23]
])
display(a)
display(a.shape)
display(a.ndim)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

(3, 4)

2

In [12]:
a = np.arange(1, 10).reshape(3,3)
display(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [14]:
b = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
b = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23],
])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
(3, 4)
int64


In [16]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[:2,1:], a[:2,1:].shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]] (2, 2)


**Pandas**

In [17]:
from IPython.display import display
import pandas as pd
a = pd.DataFrame({
        'a': [4,5,6],
        'b': [7,8,9],
        'c': [10,11,12],
    }, index = [1,2,3])
display(a)
display(a.loc[1])

b = pd.DataFrame([
    {'a':4,'b':7,'c':10},
    {'a':5,'b':8,'c':11},
    {'a':6,'b':9,'c':12},
])
display(b)
display(b.loc[1])

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

a     4
b     7
c    10
Name: 1, dtype: int64

a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

a     5
b     8
c    11
Name: 1, dtype: int64

In [18]:
display(type(a))

pandas.core.frame.DataFrame

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

s = pd.Series([1,3,5,np.nan,6,8])
display(s)

dates = pd.date_range('20181001', periods = 6)
display(dates)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [20]:
df = pd.DataFrame(np.random.randn(6,4), columns=['A','B','C','D'], index = dates)
display(df)

display(df.loc['2018-10-03'])
display(df['B'])

A         B         C         D
2018-10-01  1.456424  0.323020  0.209720 -0.073851
2018-10-02 -0.850163  1.234979  0.428952  1.142600
2018-10-03 -0.761437  0.813364 -1.601259 -0.601986
2018-10-04  2.125486  0.698541 -1.015691  0.332536
2018-10-05 -0.311690 -0.742700  1.694093 -0.115218
2018-10-06 -1.383051 -0.058810  0.389746  0.179898

A   -0.761437
B    0.813364
C   -1.601259
D   -0.601986
Name: 2018-10-03 00:00:00, dtype: float64

2018-10-01    0.323020
2018-10-02    1.234979
2018-10-03    0.813364
2018-10-04    0.698541
2018-10-05   -0.742700
2018-10-06   -0.058810
Freq: D, Name: B, dtype: float64

In [22]:
df = pd.DataFrame(np.random.randn(3,5), columns=list('ABCDE'), index = ['student1', 'student2', 'student3'])
df

A         B         C         D         E
student1 -0.732923 -0.267658 -1.590570 -1.152079 -0.247574
student2  0.781240 -0.858998  0.771715 -0.455086  0.622599
student3  0.718461  0.291536 -0.197973 -0.081528  2.941909

In [23]:
df2 = pd.DataFrame({
    'A' : 1.,
    'B' : pd.Timestamp('20181001'),
    'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
    'D' : np.array([3] * 4,dtype='int32'),
    'E' : pd.Categorical(["test","train","test","train"]),
    'F' : 'foo'
})
display(df2)

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [24]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [25]:
import pandas as pd
from IPython.display import display

# Create a DataFrame to store transactions
columns = ['Date', 'Description', 'Amount']
ledger = pd.DataFrame(columns=columns)
# display(ledger)

# Init a DataFrame to store transactions
def init_ledger():
  return pd.DataFrame(columns=columns)

# Function to add a transaction
def add_transaction(date, description, amount):
  global ledger
  new_transaction = pd.DataFrame([[date, description, amount]], columns=columns)
  ledger = pd.concat([ledger, new_transaction], ignore_index=True)

# Function to view the ledger
def view_ledger():
  display(ledger)

# Function to get the current balance
def get_balance():
  return ledger['Amount'].sum()

ledger = init_ledger()

# Adding sample transactions
add_transaction('2023-11-01', 'Income', 1000)
add_transaction('2023-11-02', 'Groceries', -300)
add_transaction('2023-11-03', 'Utilities', -200)

# Viewing the ledger
view_ledger()

# Checking the current balance
print("Current Balance:", get_balance())

Date Description Amount
0  2023-11-01      Income   1000
1  2023-11-02   Groceries   -300
2  2023-11-03   Utilities   -200

Current Balance: 500


In [26]:
import pandas as pd
df = pd.DataFrame({
    "a": [4, 5, 6],
    "b": [7, 8, 9],
    "c": [10, 11, 12]},
index = [1, 2, 3])
type(df)

pandas.core.frame.DataFrame

In [27]:
df2 = pd.DataFrame(
    {
        'A': 1.,
        'B': pd.Timestamp('20181001'),
        'C': pd.Series(2.5, index=list(range(4)), dtype='float32'),
        'D': np.array([3] * 4, dtype='int32'),
        'E': pd.Categorical(["test", "train", "test", "train"]),
        'F': 'foo'})
df2

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [28]:
df3 = pd.DataFrame(
    [
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'test', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'train', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'test', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'train', 'F': 'foo'}
    ]
)
df3

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo