<a href="https://colab.research.google.com/github/lamnguyenkhang31231021496/ueh25_ktltsp_khanglam_st3/blob/main/buoi03_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Phân tích và hiển thị dữ liệu

v = list(range(1,6))
print(v)
print(2*v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
import numpy as np
v = np.arange(1,6)
print(v)
print(v*2)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [3]:
fruits = ["apple", "banana", "cherry"] # list []
colors = ("red", "green", "blue") # tuples ()
animals = {'cat', 'dog'} # sets {}
person = {"name": "Tom", "age": 20} # dictrionaries {}

In [4]:
x = [60, 70, 80, 90]
print('len(x)', len(x))
print('x[0]=', x[0])
print('x[1]', x[1])
print('x[-1]', x[-1])
print('x[1:3]=', x[1:3])

len(x) 4
x[0]= 60
x[1] 70
x[-1] 90
x[1:3]= [70, 80]


In [6]:
from IPython.display import display
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a*b
print('c = ')
display(c)

c = 


array([ 4, 10, 18])

In [7]:
import numpy as np
a = np.zeros((2,2))
display(a)

b = np.ones((3,2))
display(b)

c = np.full((4,5), 7)
display(c)

d = np.eye(4)
display(d)

e = np.random.random((2,2))
display(e)


array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[0.32711655, 0.98371008],
       [0.52833409, 0.90348678]])

In [9]:
import numpy as np
a = np.arange(15, dtype=float)
display(a)

a = a.reshape(3,5)
display(a)

display(a.shape)
display(a.ndim)
display(a.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

(3, 5)

2

dtype('float64')

In [10]:
import numpy as np
a = np.array([1,2,3,4,5])
display(a)

array([1, 2, 3, 4, 5])

In [11]:
a = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
display(a)
display(a.shape)
display(a.ndim)
display(a.dtype)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

(4, 5)

2

dtype('int64')

In [12]:
a = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23]
])
display(a)
display(a.shape)
display(a.ndim)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

(3, 4)

2

In [13]:
a = np.arange(1,10).reshape(3,3)
display(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
display(a[2])
display(a[2].shape)

display(a[2,:])
display(a[2,:].shape)

display(a[2:,:])
display(a[2:,:].shape)

array([7, 8, 9])

(3,)

array([7, 8, 9])

(3,)

array([[7, 8, 9]])

(1, 3)

In [15]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [16]:
b = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
b = np.array([
    [0,1,2,3],
    [10,11,12,13],
    [20,21,22,23],
])
print(b)
print(b.ndim)
print(b.shape)
print(b.dtype)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
2
(3, 4)
int64


In [18]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[:2,1:], a[:2,1:].shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2]
 [4 5]] (2, 2)


In [20]:
# Pandas

from IPython.display import display
import pandas as pd
a = pd.DataFrame({
    'a': [4,5,6],
    'b': [7,8,9],
    'c': [10,11,12],
}, index = [1,2,3])
display(a)
display(a.loc[1])

b = pd.DataFrame([
    {'a':4, 'b':7, 'c':10},
    {'a':5, 'b':8, 'c':11},
    {'a':6, 'b':9, 'c':12},
])
display(b)
display(b.loc[1])

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

a     4
b     7
c    10
Name: 1, dtype: int64

a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

a     5
b     8
c    11
Name: 1, dtype: int64

In [21]:
display(type(a))

pandas.core.frame.DataFrame

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

s = pd.Series([1,3,5,np.nan,6,8])
display(s)

dates = pd.date_range('20181001', periods = 6)
display(dates)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [23]:
df = pd.DataFrame(np.random.randn(6,4), columns=['A', 'B', 'C', 'D'], index = dates)
display(df)

display(df.loc['2018-10-03'])
display(df['B'])

A         B         C         D
2018-10-01 -1.332200  0.118293 -1.822495 -1.942116
2018-10-02 -0.255248  0.082813  0.551191 -0.473593
2018-10-03  0.623347  1.121288 -0.005450  1.430245
2018-10-04  0.253002  0.414538  0.485421 -0.501191
2018-10-05  1.987941  0.039909  1.959627  0.030468
2018-10-06  0.934407  1.305372 -0.618850 -0.867600

A    0.623347
B    1.121288
C   -0.005450
D    1.430245
Name: 2018-10-03 00:00:00, dtype: float64

2018-10-01    0.118293
2018-10-02    0.082813
2018-10-03    1.121288
2018-10-04    0.414538
2018-10-05    0.039909
2018-10-06    1.305372
Freq: D, Name: B, dtype: float64

In [25]:
df = pd.DataFrame(np.random.randn(3,5), columns=list('ABCDE'), index=['student 1','student 2', 'student 3'])
df

A         B         C         D         E
student 1 -0.638033 -0.522570  0.503859 -0.122115 -0.784869
student 2 -0.655531 -0.105968  1.131523  0.507269 -0.576640
student 3 -1.438847  0.497726  1.948320  0.597279  0.445316

In [26]:
df2 = pd.DataFrame({
    'A' : 1.,
    'B' : pd.Timestamp('20181001'),
    'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
    'D' : np.array([3] * 4,dtype='int32'),
    'E' : pd.Categorical(["test","train","test","train"]),
    'F' : 'foo'
})
display(df2)

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [27]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [28]:
import pandas as pd
from IPython.display import display
# Create a DataFrame to store transactions
columns = ['Date', 'Description', 'Amount']
ledger = pd.DataFrame(columns=columns)
# display(ledger)

# Init a DataFrame to store transactions
def init_ledger():
  return pd.DataFrame(columns=columns)

# Function to add a transaction
def add_transaction(date, description, amount):
  global ledger
  new_transaction = pd.DataFrame([[date, description, amount]], columns=columns)
  ledger = pd.concat([ledger, new_transaction], ignore_index=True)

# Function to view the ledger
def view_ledger():
  display(ledger)

# Function to get the current balance
def get_balance():
  return ledger['Amount'].sum()

ledger = init_ledger()

# Adding sample transactions
add_transaction('2023-11-01', 'Income', 1000)
add_transaction('2023-11-02', 'Groceries', -200)
add_transaction('2023-11-03', 'Utilities', -100)

# Viewing the ledger
view_ledger()

# Checking the current balance
print("Current Balance:", get_balance())


Date Description Amount
0  2023-11-01      Income   1000
1  2023-11-02   Groceries   -200
2  2023-11-03   Utilities   -100

Current Balance: 700


In [29]:
import pandas as pd
df = pd.DataFrame({
    "a": [4, 5, 6],
    "b": [7, 8, 9],
    "c": [10, 11, 12]},
                  index = [1,2,3])
type(df)

pandas.core.frame.DataFrame

In [31]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randn(3,5), index=['student1','student2','student3'], columns=list('ABCDE'))

In [32]:
df2 = pd.DataFrame(
    {
        'A': 1.,
        'B': pd.Timestamp('20181001'),
        'C': pd.Series(2.5, index=list(range(4)), dtype='float32'),
        'D': np.array([3] * 4, dtype='int32'),
        'E': pd.Categorical(["test", "train", "test", "train"]),
        'F': 'foo'})
df2

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [33]:
df3 = pd.DataFrame(
    [
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'test', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'train', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'test', 'F': 'foo'},
        {'A':1.0, 'B': pd.Timestamp('20181001'), 'C': 2.5, 'D': 3, 'E': 'train', 'F': 'foo'}
    ]
)
df3

A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo